### ISSUE TITLE
Fetch collection data from API

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#12]
**Value Proposition**
As a user 
I need to connect to my collection API
to be able to access all my records and their data.

**Description**
-

**Acceptance Criteria**
 - [ ] the app shows all records that are saved in my collection on Discogs.com
 - [ ] when new records are saved in the Discogs-collection they are also visible in the app

**Tasks**
- [ ] fetch data from discogs API with authentication and user token
- [ ] refactor code where necessary to keep the rendering working

**Comment by Murci2022** [comment]
Great job Steanie! Looks good to me!
