### ISSUE TITLE
Order function behind burger menu

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#15]
**Value Proposition**
As a user 
I need to sort my collection 
to be able to find the tracks that I am looking for.

**Description**
Scribble / design or text

**Acceptance Criteria**
 - [ ] when I click on the burger menu icon a layover menu opens
 - [ ] the menu contains options to sort the collection entries by Artist, Title, Label, Year (of release), (date) added and further in ascending oder descending order
 - [ ]  when choosing a sorting order the menu closes again and the records change their order according to the choice
 - [ ] when no choice was made the menu can be closed after clicking again on the menu icon

**Tasks**
- [ ]  add burger menu icon to header
- [ ] add menu component 
- [ ] add sorting logic
- [ ] add logic to open and close the menu
