### ISSUE TITLE
Add counter for selection

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#16]
**Value Proposition**
As a user 
I need to know how many records I have selected 
to be able select the right amount that can fit in my bag.

**Description**
<img width="366" alt="Bildschirmfoto 2022-10-04 um 10 40 48" src="https://user-images.githubusercontent.com/104068626/193774786-3a0435da-f5c0-401f-ad13-817308cfc34f.png">

**Acceptance Criteria**
 - [ ] there is a counter inside the header that shows zero out of the total number of my collection when no records are selected
 - [ ] when I select records, the counter goes up and the total remains
 - [ ] when I deselect records the counter goes down
 - [ ] the counter is visible on both pages

**Tasks**
- [ ]  add counter functionality in header component
- [ ] counter is linked to state
