### ISSUE TITLE
Add youtube-videos to records

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#18]
**Value Proposition**
As a user 
I need to listen to my favourite tracks on a record 
to be able to decide what I want to put in my bag.

**Description**
<img width="298" alt="Bildschirmfoto 2022-10-06 um 16 23 57" src="https://user-images.githubusercontent.com/104068626/194338655-17fb2ae4-055e-4e47-a606-b4ed0370941c.png">

**Acceptance Criteria**
 - [x]  when I open a record file I find an input field where I can enter a YouTube-Link
 - [x] by clicking on the add button the form resets itself and a YouTube-player appears showing the preview of the video that I entered the link from
 - [x]  the player has controls to start and stop the video
 - [ ] I can add up to three videos per record

**Tasks**
- [x] within the Recordfile-component add text-form with an add-button to enter YouTube-links 
- [x] the form has a logic to extract the video-id
- [x] add iframe component that gets rendered with the video-id when the add-button is clicked
- [x] add state-/localstorage-logic to save the entered videos
