### ISSUE TITLE
Task 1: Display A List Of Records

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#2]
**Value Proposition**
As a Vinyl-DJ I need to have a list of all my records to be able to have an overview over my collection.

**Description**
![Bildschirmfoto 2022-09-14 um 15 00 10](https://user-images.githubusercontent.com/104068626/190160714-eb89bf49-0e84-4b85-9f29-70c0e57f4b74.png)

**Acceptance Criteria**
 describe every scenario in detail
 e.g. All Inputs are required, show warning if empty.
 - [ ] a header with "Record-List"
 - [ ] all record entries must contain infos on artist name, title of the record, format and year of release.
 - [ ] record entries to be created with dummy export from own collection

**Tasks**
- [ ]  create a new project with `npx create-next-app@latest`

**Comment by MerleMak** [comment]
Hi Stefanie,
Beautiful wireframes! 
I think this User Story is too big. The form should come in a future User Story. You can use dummy data to first of all render a list of entries. 
Tipp: If your title included a + sign, it is probably too big :P
Also an image upload is a lot of work and should be in another user story as well :)

**Comment by macfrei** [comment]
Just a bit of nit-picking: the acceptance criteria are notes about what the user should expect from your app. For example, what kind of products would be rendered? What happens if the products don't fit on one page? Should the page then be scrollable?

Where the data comes from and whether they are real data or dummy data should be irrelevant to the user for now. This might be a point under tasks:

```md
- [ ] record entries to be created with dummy export from own collection as JSON data
```

Or something like that. 

But the story is sweet and short and a good starting point 👍 💯
