### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#21]
**Value Proposition**
As a user 
I need a landing page 
to be able to know which app I am on and navigate to the individual pages.

**Description**
![Bildschirmfoto 2022-10-11 um 19 51 20](https://user-images.githubusercontent.com/104068626/195163951-50d0f471-93db-4d10-8065-7704f4bddea2.png)

**Acceptance Criteria**
 - [x]  when you arrive at the app you see a landing page
 - [x] the page contains some kind of slogan with the name of the app, e.g. "Get ready for your gig and pack your _RecordBag_"
 - [x] two navigation links to both pages of the app

**Tasks**
- [x] move current index.js content to new page "collection.js"
- [x] create landing page in index.js with `h1` slogan 
- [x] create two nextjs-Link elements that navigate to collection and recordbag pages
