### ISSUE TITLE
Counter for selected records

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#22]
**Value Proposition**
As a user 
I need to see how many records I have selected 
to be able to know how many I still can select to fit in my bag.

**Description**
![Bildschirmfoto 2022-10-11 um 20 10 36](https://user-images.githubusercontent.com/104068626/195167503-81277141-dc86-4ed1-bc20-30c6c772e424.png)

**Acceptance Criteria**
 - [ ]  there is a counter that shows the total amount of records and how many are selected
 - [ ] when I select a record the counter goes up
 - [ ] when I deselect a record the counter goes down

**Tasks**
- [ ]  write counter state logic connected to the records containing the property of "isChecked"
- [ ] add counter output in header on both pages
