### ISSUE TITLE
Select and Deselect Records as Bookmarked

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#3]
**Value Proposition**
As a Vinyl-DJ 
I need to select records 
to be able to prepare my record-bag for a gig.

**Description**
![Bildschirmfoto 2022-09-16 um 11 51 27](https://user-images.githubusercontent.com/104068626/190612090-450beb81-e32c-4479-b8a2-85241a522b4a.png)

**Acceptance Criteria**
 - [x] records can be marked as selected
 - [x] they can also be deselected by clicking again on the marker

**Tasks**
- [x] add bookmark icons to record files
- [x] write bookmark toggle logic to add the marked records to a new state
