### ISSUE TITLE
Save Them in RecordBag

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#6]
**Value Proposition**
As a Vinyl-DJ 
I need to view my selected records
to be able to prepare my record-bag for a gig.

**Description**
![Bildschirmfoto 2022-09-16 um 11 46 19](https://user-images.githubusercontent.com/104068626/190610899-7ef5d754-4dd7-4431-a6e7-9e0274ba6340.png)

**Acceptance Criteria**
 - [ ] selected records can be found in new frame called "RecordBag"
 - [ ] when records are deselected they are removed from the RekordBag
 - [ ] in a navigation bar you can change between RekordCollection and RecordBag
 - [ ] the navigation bar shows which page is active

**Tasks**
- [ ] create new frame that renders only the bookmarked records
- [ ] create footer navbar with icon buttons to switch between frames
- [ ] write logic to mark navbar icon of the current page as active
