### ISSUE TITLE
Toggle showing/hiding track information for each record

### ISSUE THREAD

**Issue by StefanieLoeser** [StefanieLoeser/capstone-project#7]
**Value Proposition**
As a user
I need to view all tracks that are on a record
to be able to prepare my playlist.

**Description**
![Bildschirmfoto 2022-09-16 um 16 45 40](https://user-images.githubusercontent.com/104068626/190666521-abb37497-8f4e-4def-9894-cc058e6f1095.png)

**Acceptance Criteria**
 - [x] record file can be toggled to extend
 - [x] the extended file shows information about all tracks on the record, which side and position they are on and how long they are
 - [x] when the file is opened you can close it again by clicking on a "^"-button

**Tasks**
- [x] fetch further information, for now still from dummy data
- [x] render all record files in collection with track information but set them hidden
- [x] add toggle logic to extend the record file when clicking on any point of the file 
- [x] add "close"-button that closes the record file to its initial size and hides the track information
